language: c
install: apt-get install valgrind
script: cmake . && make && make test && valgrind --error-exitcode=1 ./bdsm_test
compiler: 
  - gcc
  - clang
notifications:
  email:
    recipients:
      - sopindm@gmail.com
